### ISSUE TITLE
Use old or new TAT for limiting decision?

### ISSUE THREAD

**Issue by DaveCTurner** [throttled/throttled#22]
Not really an issue so much as a question here. As directed in [1] I'm reading this code in order to understand a bit more about GCRA. At [2] you compare the request arrival time against `newTat` when deciding whether a request should be limited or not, but my reading of the description on GCRA (e.g. on Wikipedia) is that this comparison should be against the previous value `tat`.

Am I reading this wrong? If not, does this matter?

Many thanks,

[1] https://brandur.org/rate-limiting
[2] https://github.com/throttled/throttled/blob/master/rate.go#L200

**Comment by brandur** [comment]
Hey @DaveCTurner,

So I think you're probably right, but the code as implemented may a bit of a simplification/optimization to get to the next result we can calculate against and store in Redis with fewer calculations.

It might be a little easier to approach this from the other way: we could compare against `tat` instead of `newTAT` here, but then we wouldn't be considering the size of the current action. You can see by the calculation of the delay variation tolerance (DVT) that we explicitly consider bucket size _plus one_ to make sure that we can account for a single action that is occurring right now [1]. I personally find this a little easier to reason about if I consider the maximum bucket size to be zero, and so the DVT is always just `1 * emissionInterval`.

I hope this helps somewhat (but I may have just made it even more confusing).

[1] https://github.com/throttled/throttled/blob/master/rate.go#L150

**Comment by DaveCTurner** [comment]
Yes, I think that helps. Basically the original GCRA only allowed for limiting the number of requests whereas here you're limiting the total size, so you need to account for the size of the next request too. To seek a parallel with the leaky bucket approach you should always reject a request larger than the bucket even if the bucket started out empty.

You're right, it does make more sense that way. I guess it was a bit computationally quicker to account for the next request when you knew it had unit size which is why that's done in canonical GCRA. Proving that this algorithm does actually limit the rate seems more straightforward with your approach.

Thanks for the help.

**Comment by DaveCTurner** [comment]
> Proving that this algorithm does actually limit the rate seems more straightforward with your approach.

... because it's false if you use the old value!

More precisely, using the new value is equivalent to using the old value _together with_ a limit on the size of each request. If the requests are not bounded in size then a sequence of requests of size 2^(2^n) would be acceptable when using the old value, but has unbounded rate.

Cool.

**Comment by brandur** [comment]
Glad this helped a bit. And yep, your explanation above is better than mine was :)

**Comment by DaveCTurner** [comment]
Thanks. I thought my notes were worth writing up, as it doesn't seem to be very well explained in the literature and once I'd found the right picture to draw it all fell into place. So here they are:

https://twitter.com/DaveCTurner/status/804400816991911936

Enjoy!

**Comment by brandur** [comment]
@DaveCTurner That is _insanely_ cool. Nice!

**Comment by metcalf** [comment]
If only we could add that picture to the Wikipedia entry!
