### ISSUE TITLE
No expiration for 0 TTLs in redis store

### ISSUE THREAD

**Issue by tobischo** [throttled/throttled#26]
While taking a closer look at throttled I noticed that keys with a TTL of 0 are not expired, which makes sense since redis does not support 0 as a value for setting an expiration.
That would also mean that a key is never removed from the store even if there aren't any requests for quite a while.
Is there a specific reason for this?

**Comment by brandur** [comment]
Oof, yep, I think this is a bug.

According to [`EXPIRE`'s documentation](https://redis.io/commands/expire):

> Note that calling EXPIRE/PEXPIRE with a non-positive timeout or EXPIREAT/PEXPIREAT with a time in the past will result in the key being deleted rather than expired (accordingly, the emitted key event will be del, not expired).

So instead of leaving the key in the store forever, that would just delete it immediately. However, there's another `if` conditional around the call to `EXPIRE` so in practice we'd just leave the key in Redis forever.

A console demonstration:

```
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> expire foo 0
(integer) 1
127.0.0.1:6379> get foo
(nil)
```

`SETEX` is a little different even because it'll actually error if called with an expiry of 0 and we don't have a conditional to check for that as far as I can tell:

```
127.0.0.1:6379> setex foo 0 bar
(error) ERR invalid expire time in setex
```

Anyway, hopefully this won't happen to most users because it depends on a fast rate that replenishes in less than a second, but for sure we should fix it anyway. I propose that we simply use set a minimum TTL of one second. I've issued a pull over in #27.

Thanks for the report!

**Comment by tobischo** [comment]
OK, great 👍  So I didn't misunderstand it/missed something. Thanks for already creating a pull request. I just wanted clarification before making any attempt of fixing it.

**Comment by brandur** [comment]
Cool! I don't look at this code too often, so it'd be nice to get one more review, but I think you're right about this.
