### ISSUE TITLE
Consider to remove import path check

### ISSUE THREAD

**Issue by wjkohnen** [throttled/throttled#31]
Throttled uses a [import path check](https://golang.org/cmd/go/#hdr-Import_path_checking), forcing an import path of `gopkg.in/throttled/throttled.v2`. gopkg.in is basically a "dependency management as a service". With the plethora of available dependency management tools and the advent of `dep`, gopkg.in has become obsolete and forcing to use it is unnecessarily limiting.

**Comment by brandur** [comment]
Fair point. `gopkg.in` also makes development unreasonably difficult due to a differing repository URL and import path that are painful to reconcile.

Given that throttled's API has been almost perfectly stable for two years now and that `dep` actually supports something resembling real dependency management (it locks to version tags like `v2.0.0.0`), I'd be in favor of making this change.

@metcalf Any thoughts on this one?

**Comment by metcalf** [comment]
Yep, I'd be in favor of making this change now that the dependency story in
Golang is clearer. @brandur want me to tackle this or do you want to?

**Comment by brandur** [comment]
@metcalf I'll take it if you're willing to review!

**Comment by brandur** [comment]
Gopkg has been dropped and the new `master` is tagged at v2.1.0.
